<template>
    <div class="bg-yellow-500 py-8 h-auto text-center">    
        
        <h1 class="text-3xl mb-3 font-hairline">ENG2003 Course Reflection</h1>
        <p class="text-md md:px-64 px-4 mb-4">
            At the start of the semester, my intention was to take this course for granted, similar to how everyone ignores the impact of communication. Since the start of my time at Lassonde, I've noticed that effective communication is not a skill that many engineers prioritize compared to computational and analytical skills, myself included. Concepts such as the rhetorical triangle and the axioms of communication on the surface seem like theoretical formalities rather than usable intelligence that can help one achieve their goal through communicating. After going through the process of applying to summer internships, I look back on all the professional correspondence, in-person interviews, and cover letters that I have communicated through. I realize that through these different mediums, I can still recognize the fundamental axioms and rhetoric I used to achieve my goal of an internship. ENG2003 gave me the confidence to write professional correspondence and network effectively using pathos/ethos/logos. 
            <br><br>
            An extremely helpful activity was writing a mock cover letter for a position that was extremely similar to many of the positions I applied to. Using the feedback from that assignment, I was able to write a cover letter that eventually got me a job offer. Another extremely helpful activity was the mock video interview. A large percentage of the jobs I applied to required video interviews, since this was unfamiliar to me I approached them with nervousness and uncertainty of my performance. Thankfully, the mock interview allowed me to receive feedback on communication attributes such as my tone, volume, and staccatos. Additionally, one of my long term academic goals is to write and publish a machine learning oriented paper. However, this is an incredibly daunting scholarly task and is something I have never had any experience with. The technical report assignment was a significant exercise which I believe helped me move towards this goal. 
            <br><br>
            I believe my technical writing skills have improved dramatically, which I can attribute to the use of peer assessments and multiple editorial reviews. Having multiple reviewers helped me to attain different perspectives on my writing and it has helped me realized the importance of collaborative writing. To conclude, my communication skills were greatly improved by this course and I now have the confidence to apply my skills as a renaissance engineer in the workforce and academia.   
        </p>

        <h1 class="text-3xl mb-3 font-hairline">My Growth as an Engineering Communicator</h1>
        <p class="text-md md:px-64 px-4">
            Throughout high school, I was really disheartened by my communication abilities and was not confident in them. As such, I had relatively low marks in liberal arts courses and felt as if I would never be able to communicate my ideas effectively. When I entered university, one of my main goals was to improve my communication skills for purposes more meaningful than Shakespeare and abstract ideologies. I wanted to improve the way I created informative, professional, and technical writing. Furthermore, I know that I could improve my skills as a software engineer by leveraging communicative techniques such as conciseness and abstraction. 
            <br><br>
            Through the confidence I've gained in this course, I have expanded my literary hobbies into two fields, podcasting and writing educational articles. After numerous opportunities to showcase my oral presentation skills, I started a podcast tailored to software engineering students. By leveraging the techniques in ENG2003, I believe I have been able to relate and communicate with my audience more effectively. I also have taken up writing educational articles on engineering and computer science, mainly to explain topics, which I found difficult, concisely and simply. 
            <br><br>
            In summation, I think that I have grown as a communicator and have more confidence in my abilities as a direct result of things I have learned from this course. The skills that I have learned from ENG2003 have benefited me in my other classes at York and have also helped me in my forays into the workforce. I truly believe that the information that I have learned from this course will benefit me for the rest of my professional and academic career.
        </p>
    </div>
</template>