<template>
    <div class="bg-yellow-500 py-8 h-auto text-center">    
        <h1 class="text-4xl mb-3 font-hairline tracking-wider">REFLECTION</h1>
        <p class="text-md md:px-64 px-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam posuere mi tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel dolor id felis elementum fermentum. Fusce at malesuada ex, quis cursus mauris. In eu turpis rhoncus, dignissim ipsum ut, eleifend leo. Phasellus ac cursus odio, non vulputate justo. Curabitur porta placerat mollis. Duis eu felis sit amet eros imperdiet ullamcorper. Maecenas euismod nibh nisl, quis pretium ex gravida sit amet. Phasellus sagittis diam a dapibus tincidunt. Pellentesque fermentum mi odio, sit amet lobortis ligula auctor et. Cras lacus orci, porttitor sit amet viverra quis, cursus et lectus. Nulla ultrices tellus vel molestie fringilla. Phasellus suscipit, velit dignissim sagittis laoreet, ante odio imperdiet nulla, eu finibus arcu ipsum quis augue. 
            <br><br>
            Cras placerat elementum tempus. Nunc iaculis nisi ut ante egestas tincidunt. Nunc dapibus rhoncus quam sit amet interdum. Donec a augue et massa placerat iaculis. Nunc malesuada lorem ultricies tincidunt mattis. Quisque eu ante libero. Duis ipsum metus, viverra non quam at, semper vehicula justo. Vestibulum felis lacus, lacinia quis mollis at, convallis vel erat. Suspendisse id mauris massa. Phasellus diam justo, tristique quis mi eget, egestas ultrices enim. Suspendisse hendrerit magna id pretium varius. Nunc ornare placerat commodo. Nulla viverra tempus justo, non porta ex semper aliquam. Fusce dapibus lorem nec odio vehicula, at sodales neque suscipit. Quisque sit amet vulputate urna. Nunc varius facilisis nulla, eget pharetra libero iaculis vitae. 
            <br> <br>
            Nunc ac porttitor neque. Aliquam imperdiet quis ligula fringilla feugiat. Praesent congue metus sit amet facilisis vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In hac habitasse platea dictumst. Sed convallis viverra diam vitae efficitur. Nunc aliquet dui nec tincidunt auctor. In lacinia ut velit ac bibendum. Sed ac magna quis dui pulvinar eleifend in accumsan justo. Donec ornare dui ut tortor vestibulum, ac fringilla sapien suscipit. Sed porta, quam id condimentum porttitor, nunc neque lacinia diam, vitae ornare nisl dolor sit amet augue. Fusce metus nulla, egestas ac aliquet a, feugiat luctus ex. Aenean sit amet sem eu metus tempus luctus. Nunc tincidunt turpis quis ullamcorper accumsan. Vivamus dignissim odio et tortor porttitor accumsan. Nulla augue est, gravida tempus lorem vel, malesuada accumsan ante. 
        </p>
    </div>
</template>